FROM oven/bun:1.0.26-slim as base

FROM base AS build

WORKDIR /app
COPY package.json bun.lockb ./

ENV VITE_APP_API_URL=http://localhost:8000/api/v1
ENV VITE_APP_AWS_S3_BUCKET_URL=https://nplanstorage.s3.ap-southeast-2.amazonaws.com
ENV NODE_ENV=production

RUN bun install --frozen-lockfile
COPY . .
RUN bun run build

FROM caddy:2.6.2-alpine AS deploy
EXPOSE 443

COPY --from=build /app/dist /usr/share/caddy
