"""second_init

Revision ID: 14c7201e6bcf
Revises: 5354ecfd1945
Create Date: 2024-07-04 10:54:19.098679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14c7201e6bcf'
down_revision = '5354ecfd1945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
