"""categories

Revision ID: 472cbc886582
Revises: e1051675ac1d
Create Date: 2024-07-08 06:22:39.454104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472cbc886582'
down_revision = 'e1051675ac1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_category_level_id'), 'category_level', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('scoreboard',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('upload_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_scoreboard_upload_count'), 'scoreboard', ['upload_count'], unique=False)
    op.create_index(op.f('ix_scoreboard_user_id'), 'scoreboard', ['user_id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category_level.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'category_id', name='subject_id_category_id_unique'),
    sa.UniqueConstraint('name', 'category_id', name='category_level_name_unique')
    )
    op.create_index(op.f('ix_subjects_category_id'), 'subjects', ['category_id'], unique=False)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_table('library.py',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('view_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('extension', sa.String(), server_default='.pdf', nullable=False),
    sa.ForeignKeyConstraint(['category'], ['category_level.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['subject', 'category'], ['subjects.id', 'subjects.category_id'], ),
    sa.ForeignKeyConstraint(['subject'], ['subjects.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['type'], ['documents.id'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['account.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    op.create_index(op.f('ix_library.py_approved'), 'library.py', ['approved'], unique=False)
    op.create_index(op.f('ix_library.py_category'), 'library.py', ['category'], unique=False)
    op.create_index(op.f('ix_library.py_document_name'), 'library.py', ['document_name'], unique=False)
    op.create_index(op.f('ix_library.py_id'), 'library.py', ['id'], unique=False)
    op.create_index(op.f('ix_library.py_subject'), 'library.py', ['subject'], unique=False)
    op.create_index(op.f('ix_library.py_type'), 'library.py', ['type'], unique=False)
    op.create_index(op.f('ix_library.py_uploaded_on'), 'library.py', ['uploaded_on'], unique=False)
    op.create_index(op.f('ix_library.py_year'), 'library.py', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_library.py_year'), table_name='library.py')
    op.drop_index(op.f('ix_library.py_uploaded_on'), table_name='library.py')
    op.drop_index(op.f('ix_library.py_type'), table_name='library.py')
    op.drop_index(op.f('ix_library.py_subject'), table_name='library.py')
    op.drop_index(op.f('ix_library.py_id'), table_name='library.py')
    op.drop_index(op.f('ix_library.py_document_name'), table_name='library.py')
    op.drop_index(op.f('ix_library.py_category'), table_name='library.py')
    op.drop_index(op.f('ix_library.py_approved'), table_name='library.py')
    op.drop_table('library.py')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_category_id'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_scoreboard_user_id'), table_name='scoreboard')
    op.drop_index(op.f('ix_scoreboard_upload_count'), table_name='scoreboard')
    op.drop_table('scoreboard')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_category_level_id'), table_name='category_level')
    op.drop_table('category_level')
    # ### end Alembic commands ###
