"""

Revision ID: 5354ecfd1945
Revises: b691cdff2942
Create Date: 2024-07-04 09:50:54.187312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5354ecfd1945'
down_revision = 'b691cdff2942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
