"""init

Revision ID: 7739029db16a
Revises: c0affd88aeb1
Create Date: 2024-07-02 19:16:20.644247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7739029db16a'
down_revision = 'c0affd88aeb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('email', sa.String(), nullable=True))
    op.add_column('account', sa.Column('role', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('account', sa.Column('verified', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('account', sa.Column('email_verification_token', sa.String(), nullable=True))
    op.add_column('account', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'account', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='unique')
    op.drop_column('account', 'reset_password_token')
    op.drop_column('account', 'email_verification_token')
    op.drop_column('account', 'verified')
    op.drop_column('account', 'role')
    op.drop_column('account', 'email')
    # ### end Alembic commands ###
