"""Revision ID: 94c58e9a847d
Revises: 7739029db16a
Create Date: 2024-07-02 19:19:09.785179
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c58e9a847d'
down_revision = '7739029db16a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
