"""second_init

Revision ID: b691cdff2942
Revises: 94c58e9a847d
Create Date: 2024-07-04 08:28:53.407172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b691cdff2942'
down_revision = '94c58e9a847d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
