"""init

Revision ID: c0affd88aeb1
Revises: e1051675ac1d
Create Date: 2024-07-02 07:41:07.191796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0affd88aeb1'
down_revision = 'e1051675ac1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
